### PR TITLE
Restructure site for i18n

### PR DESCRIPTION
**Pull request by xldrkp**
Hi @ShweataNHegde, I have not changed a thing in the content but prepared the site for future translations. Please have a look at my log in Slack and [the Hedgedoc](https://writemd.rz.tuhh.de/cnT4bj1XS5ihu4dqpzwQZw?view) I wrote.

### CODE REVIEW

**Comment by ShweataNHegde** [comment]
### <span aria-hidden="true">✅</span> Deploy Preview for *semanticclimate* ready!


|  Name | Link |
|---------------------------------|------------------------|
|<span aria-hidden="true">🔨</span> Latest commit | 7d0552af159b23ba7d44c0920a24ad972799aa62 |
|<span aria-hidden="true">🔍</span> Latest deploy log | https://app.netlify.com/sites/semanticclimate/deploys/634c3c30d27d5600084e1889 |
|<span aria-hidden="true">😎</span> Deploy Preview | [https://deploy-preview-6--semanticclimate.netlify.app](https://deploy-preview-6--semanticclimate.netlify.app) |
|<span aria-hidden="true">📱</span> Preview on mobile | <details><summary> Toggle QR Code... </summary><br /><br />QR Code<br /><br />_Use your smartphone camera to open QR code link._</details> |
---

_To edit notification comments on pull requests, go to your [Netlify site settings](https://app.netlify.com/sites/semanticclimate/settings/deploys#deploy-notifications)._

**Comment by ShweataNHegde** [comment]
Thanks so much, Axel! I'm new to having translations on websites, so this is useful. Do we create these `en` and `de` files manually for every language?

**Comment by xldrkp** [comment]
@ShweataNHegde I wouldn't think so. Five years ago I lead a project where we translated German to Farsi and English with [Crowdin](https://crowdin.com/), see https://crowdin.com/project/hop-on. You connect this service to your repo and define where the file are that need translation. Translators do their work in the Crowdin backend. When they save their work, Crowdin make a commit to a special branch in the repo that you then merge. For every language you translate a new folder with the language `en` or `de` or whatever gets created. So, short answer: You don't need to create the files manually. Yesterday I build the structure to prepare this in case you want to translate the page later. If we switched the static site generator later the URLs should already be well-structured.

**Comment by xldrkp** [comment]
@ShweataNHegde Do you think we should do the migration tomorrow? The content of the current site needs to be moved, too.

**Comment by ShweataNHegde** [comment]
Okay, now it makes sense. I'll go ahead and merge the PR. We can work on migration today.

**Pull request merged**
